modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="horizondata"
version="1.0.0"
displayName="HorizonData"
description="Foundational materials for Horizon Corebreach."

[[dependencies.horizondata]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="NONE"
side="BOTH"

[[dependencies.horizondata]]
modId="horizoncore"
type="required"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"